application: shell909090
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: .*
  script: wsgi.application
  secure: optional

- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt
