application: <%youappid%>
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: pycrypto
  version: latest

handlers:
- url: .*
  script: wsgi.application
  secure: optional

- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt
